apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-configmap
  labels:
    app: payment-service
data:
  DB_HOST: "$DB_HOST"
  DB_PORT: "$DB_PORT"
  DB_USERNAME: "$DB_USERNAME"
  DB_PASSWORD: "$DB_PASSWORD"
