apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: payment-service-configmap
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"