apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: payment-service
  namespace: payment-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70